# Generated by Django 5.2.5 on 2026-03-30 07:17

import Certifier_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certifier_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(default=Certifier_App.models.generate_certificate_id, max_length=100, unique=True),
        ),
    ]
