# Generated by Django 5.2.5 on 2026-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certifier_App', '0003_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='recipient_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
