# Generated by Django 5.2.5 on 2026-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certifier_App', '0004_certificate_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='event_logo',
            field=models.ImageField(blank=True, null=True, upload_to='templates/event_logos/'),
        ),
    ]
